STATUS_ERROR = 500
STATUS_SUCCESS = 200
STATUS_NOT_FOUND = 404
STATUS_BAD_REQUEST = 400
STATUS_CONFLICT = 409
STATUS_ACCEPTED = 201
STATUS_UNAUTHORIZED = 401

MIME_TEXT = 'text/plain'
MIME_JSON = 'application/json'